const sidebars = {
	sidebar: [{ type: "autogenerated", dirName: "." }]
	// If you decide to split docs into sections (E.g. Docs & Reference), check out https://docusaurus.io/docs/sidebar/multiple-sidebars
}

module.exports = sidebars

